# Generated by Django 5.2 on 2025-05-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CitaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Descripcion', models.TextField()),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.estadocita')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cita_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.citaventa')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
