# Generated by Django 5.2 on 2025-05-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(default='no hay descripcion', max_length=80, null=True),
        ),
    ]
