# Generated by Django 5.2 on 2025-05-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_alter_permiso_rol_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
    ]
