# Generated by Django 5.2 on 2025-05-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='insumoAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Uso', max_length=30)),
                ('abastecimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimiento.abastecimiento')),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
            ],
        ),
    ]
