# Generated by Django 5.2 on 2025-05-28 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='estado',
            field=models.CharField(choices=[('Sin reportar', 'Sin Reportar'), ('Reportado', 'Reportado')], default='Sin reportar', max_length=30),
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 5, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='fecha_reporte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumoabastecimiento',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insumoabastecimiento',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumoabastecimiento',
            name='estado',
            field=models.CharField(choices=[('Acabado', 'Acabado'), ('Uso medio', 'Uso medio'), ('Bajo', 'Bajo'), ('Sin usar', 'Sin usar')], default='Sin usar', max_length=30),
        ),
    ]
