# Generated by Django 5.2 on 2025-06-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0006_alter_usuario_options_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_correo',
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_username',
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_documento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=60, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='api_usuario_groups', related_query_name='usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_usuario_user_permissions', related_query_name='usuario', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
