# Generated by Django 5.2 on 2025-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_options_remove_usuario_unique_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
