# Generated by Django 5.2 on 2025-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_cliente_correo_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manicurista',
            name='celular',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='manicurista',
            name='correo',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='manicurista',
            name='numero_documento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
