# Generated by Django 5.2 on 2025-05-01 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(default=django.utils.timezone.now)),
                ('fechaCompra', models.DateField(default=django.utils.timezone.now)),
                ('IVA', models.DecimalField(decimal_places=2, default=0.19, max_digits=10)),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
                ('estadoCompra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.estadocompra')),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precioUnitario', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
            ],
        ),
    ]
