# Generated by Django 5.2 on 2025-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
