# Generated by Django 5.2 on 2025-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('Manicure', 'Manicure'), ('Pedicure', 'Pedicure'), ('Uñas acrílicas', 'Uñas Acrílicas')], default='Manicure', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=40),
        ),
    ]
