# Generated by Django 5.2 on 2025-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_servicio_tipo_alter_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='url_imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
