# Generated by Django 5.2 on 2025-06-06 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_servicio_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
