# Generated by Django 5.2 on 2025-06-06 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_servicio_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
