# Generated by Django 5.2 on 2025-06-06 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_servicio_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='hora',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
