# Generated by Django 5.2 on 2025-06-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 'Muy Bien'), (2, 'Bien'), (3, 'Mal'), (4, 'Muy Mal')])),
                ('comentario', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='calificaciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
