# Generated by Django 5.2 on 2025-05-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicial', models.DateField()),
                ('TotalGenerado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Local', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FechaFinal', models.DateField()),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('HoraEntrada', models.TimeField()),
                ('HoraSalida', models.TimeField()),
                ('Motivo', models.TextField()),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.manicurista')),
            ],
        ),
    ]
