# Generated by Django 5.2 on 2025-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('representante', models.CharField(max_length=60)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'NATURAL'), ('JURIDICA', 'JURIDICA')], max_length=8)),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'cedula de ciudadania')], max_length=3)),
                ('numero_documento', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
            ],
        ),
    ]
