# Generated by Django 5.2 on 2025-05-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='representante',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellido_representante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
