# Generated by Django 5.2 on 2025-05-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_remove_proveedor_representante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
