# Generated by Django 5.2 on 2025-05-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_remove_proveedor_nombre_proveedor_nombre_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_representante',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_persona',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica')], max_length=10),
        ),
    ]
