# Generated by Django 5.2 on 2025-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_alter_proveedor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
