# Generated by Django 5.2 on 2025-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0007_alter_proveedor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
    ]
