# Generated by Django 5.2 on 2025-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('bajo', 'bajo'), ('agotado', 'agotado')], default='Activo', max_length=9),
        ),
    ]
