# Generated by Django 5.2 on 2025-05-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_rename_cantidad_insumo_stock_insumo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bajo', 'Bajo'), ('Agotado', 'Agotado')], default='Activo', max_length=9),
        ),
    ]
