# Generated by Django 5.2 on 2025-05-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_alter_insumo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='marca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.marca'),
        ),
    ]
